services:
  forsaj-backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    restart: unless-stopped
    environment:
      PORT: "3001"
      WEB_DATA_DIR: "/app/data/web-data"
      ADMIN_PUBLIC_DIR: "/app/data/web-data"
      UPLOAD_DIR: "/app/data/uploads"
    volumes:
      - /datastore/forsaj/data:/app/data
    networks:
      - edge
    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=edge'
      - 'traefik.http.routers.forsaj-api.rule=(Host(`forsaj.octotech.az`) || Host(`forsaj.az`) || Host(`admin.forsaj.octotech.az`) || Host(`admin.forsaj.az`)) && (PathPrefix(`/api`) || PathPrefix(`/uploads`))'
      - 'traefik.http.routers.forsaj-api.entrypoints=web,websecure'
      - 'traefik.http.routers.forsaj-api.tls=true'
      - 'traefik.http.routers.forsaj-api.priority=300'
      - 'traefik.http.services.forsaj-api.loadbalancer.server.port=3001'

  forsaj-frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    restart: unless-stopped
    networks:
      - edge
    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=edge'
      - 'traefik.http.routers.forsaj.rule=Host(`forsaj.octotech.az`) || Host(`forsaj.az`) || Host(`admin.forsaj.octotech.az`) || Host(`admin.forsaj.az`)'
      - 'traefik.http.routers.forsaj.entrypoints=web,websecure'
      - 'traefik.http.routers.forsaj.tls=true'
      - 'traefik.http.routers.forsaj.priority=100'
      - 'traefik.http.services.forsaj.loadbalancer.server.port=80'

  forsaj-admin:
    build:
      context: .
      dockerfile: Dockerfile.admin
    restart: unless-stopped
    networks:
      - edge
    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=edge'
      - 'traefik.http.routers.forsaj-admin.rule=(Host(`forsaj.octotech.az`) || Host(`forsaj.az`) || Host(`admin.forsaj.octotech.az`) || Host(`admin.forsaj.az`)) && PathPrefix(`/admin`)'
      - 'traefik.http.routers.forsaj-admin.entrypoints=web,websecure'
      - 'traefik.http.routers.forsaj-admin.tls=true'
      - 'traefik.http.routers.forsaj-admin.priority=200'
      - 'traefik.http.services.forsaj-admin.loadbalancer.server.port=80'

networks:
  edge:
    external: true
