services:
  forsaj-backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    restart: unless-stopped
    environment:
      PORT: "5000"
      WEB_DATA_DIR: "/app/data/web-data"
      ADMIN_PUBLIC_DIR: "/app/data/web-data"
      UPLOAD_DIR: "/app/data/uploads"
      SUPABASE_URL: "https://mrgnxibkjqsyolidyelp.supabase.co"
      SUPABASE_ANON_KEY: "sb_publishable_6WzNDxYgXsTlShf4W2Y97w_lJefRrz4"
      SUPABASE_SERVICE_ROLE_KEY: "${SUPABASE_SERVICE_ROLE_KEY}"
      VITE_SUPABASE_URL: "https://mrgnxibkjqsyolidyelp.supabase.co"
      VITE_SUPABASE_ANON_KEY: "sb_publishable_6WzNDxYgXsTlShf4W2Y97w_lJefRrz4"
    volumes:
      - /datastore/forsaj/data:/app/data
    networks:
      - edge
    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=edge'
      - 'traefik.http.routers.forsaj-api.rule=Host(`forsaj.octotech.az`) && (PathPrefix(`/api`) || PathPrefix(`/uploads`))'
      - 'traefik.http.routers.forsaj-api.entrypoints=web'
      - 'traefik.http.routers.forsaj-api.priority=1500'
      - 'traefik.http.services.forsaj-api.loadbalancer.server.port=5000'

  forsaj-frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
      args:
        VITE_SUPABASE_URL: "https://mrgnxibkjqsyolidyelp.supabase.co"
        VITE_SUPABASE_ANON_KEY: "sb_publishable_6WzNDxYgXsTlShf4W2Y97w_lJefRrz4"
    restart: unless-stopped
    networks:
      - edge
    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=edge'
      - 'traefik.http.routers.forsaj.rule=Host(`forsaj.octotech.az`)'
      - 'traefik.http.routers.forsaj.entrypoints=web'
      - 'traefik.http.routers.forsaj.priority=500'
      - 'traefik.http.services.forsaj.loadbalancer.server.port=80'

  forsaj-admin:
    build:
      context: .
      dockerfile: Dockerfile.admin
    restart: unless-stopped
    networks:
      - edge
    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=edge'
      - 'traefik.http.routers.forsaj-admin.rule=Host(`forsaj.octotech.az`) && PathPrefix(`/admin`)'
      - 'traefik.http.routers.forsaj-admin.entrypoints=web'
      - 'traefik.http.routers.forsaj-admin.priority=1000'
      - 'traefik.http.services.forsaj-admin.loadbalancer.server.port=80'

  forsaj-db:
    image: mysql:8.0
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "forsaj_admin"
      MYSQL_USER: "forsaj_user"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    volumes:
      - /datastore/forsaj/mysql:/var/lib/mysql
    networks:
      - edge
    labels:
      - 'traefik.enable=false'

networks:
  edge:
    external: true
